"""Refresh public signature/property facts from the independently built reference.
Usage: python tools/generate-tables.py /absolute/path/to/promql-reference
Run from the repository root. No implementation code is imported into MoonBit.
"""
from pathlib import Path
import json,subprocess,sys

def reference(requests):
    result=subprocess.run([sys.argv[1]],input='\n'.join(json.dumps(x) for x in requests)+'\n',encoding='utf8',capture_output=True,check=True)
    replies=[json.loads(line) for line in result.stdout.splitlines()]
    assert len(replies)==len(requests),'reference response count'
    assert not any('adapterError' in r for r in replies),replies
    return replies

metadata=reference([{'metadata':True}])[0]
names=sorted(set(metadata['unicodeProperties']))
results=reference([{'regex':'\\p{'+name+'}'} for name in names])
valid=[name for name,result in zip(names,results) if result['accepted']]
metadata['validatedRegexUnicodeProperties']=valid
types={'scalar':'Scalar','vector':'InstantVector','matrix':'RangeVector','string':'StringValue'}
out=['// API facts derived from Prometheus v3.14.0 (Apache-2.0); see THIRD_PARTY_NOTICES.md.',
     '// Generated by tools/generate-tables.py using the unmodified reference parser.','///|',
     'pub(all) struct FunctionSignature {',
     '  name : String; arguments : Array[QueryType]; min_args : Int; max_args : Int?',
     '  result : QueryType; experimental : Bool',
     '} derive(Debug, Eq, ToJson)','///|',
     'fn function_signature(name : String) -> FunctionSignature? {','  match name {']
functions=metadata['functions']
for name,signature in sorted(functions.items()):
    args=signature['ArgTypes'] or []
    variadic=signature['Variadic']
    minimum=len(args)-(1 if variadic else 0)
    maximum=minimum+variadic if variadic>0 else len(args) if variadic==0 else None
    out.append(f'    "{name}" => Some({{name, arguments:[{",".join(types[a] for a in args)}], min_args:{minimum}, max_args:{"None" if maximum is None else f"Some({maximum})"}, result:{types[signature["ReturnType"]]}, experimental:{str(signature["Experimental"]).lower()}}})')
out+=['    _ => None','  }','}','///|','pub fn function_signatures() -> Array[FunctionSignature] {',
      '  ['+','.join(json.dumps(name) for name in sorted(functions))+'].map(name => function_signature(name).unwrap())','}']
Path('function_table.mbt').write_text('\n'.join(out)+'\n',encoding='utf8',newline='\n')
Path('regex_properties.mbt').write_text('// Validated Unicode property names from the pinned Go/RE2 reference; see THIRD_PARTY_NOTICES.md.\n///|\nfn regex_property(name : String) -> Bool {\n  ['+','.join(json.dumps(n) for n in valid)+'].contains(name)\n}\n',encoding='utf8',newline='\n')
Path('evidence/reference-metadata.json').write_text(json.dumps(metadata,ensure_ascii=False,indent=2)+'\n',encoding='utf8',newline='\n')
print(f'Generated {len(functions)} function signatures and {len(valid)} independently validated Unicode property names')
